blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.PostListView.as_view(), name='home'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('csv/',views.Some_view, name='csv'),
    path('highlight/<int:pk>/',views.HighlightView.as_view(), name='hightlight'),
    path('pdf/',views.pdf_view, name='pdf'),
    path('new/', views.NewPostView.as_view(), name='post_new'),
    path('<int:pk>/update/', views.PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('today/', views.PostTodayArchiveView.as_view(),name="today_post"),
    path('archive/', views.PostArchiveIndexView.as_view(),name="today_archive"),
    path('<int:year>/', views.PostYearArchiveView.as_view(),name="post_year_archive"),
    path('<int:year>/<int:month>/', views.PostMonthArchiveView.as_view(month_format="%m"),name="archive_month_numeric"),
    path('<int:year>/<str:month>/', views.PostMonthArchiveView.as_view(),name="archive_month"),

    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('about/', views.about_me, name='about_me'),
    path('books/', views.ImageView.as_view(), name='books'),
    path('upload/', views.ImageUploadView.as_view(), name='image_upload'),
    path('', views.post_list, name='home'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
                                 name='django.contrib.sitemaps.views.sitemap'),
    path('markdownx/', include('markdownx.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

blog/models.py
# blog/models.py

import mistune
from django.db.models import Count
from django import template

from pygments import highlight
from pygments.lexers import get_lexer_by_name
from pygments.formatters import HtmlFormatter

class HighlightRenderer(mistune.Renderer):
    def block_code(self, code, lang):
        print("code")
        print(code)
        print()
        print("language")
        print(lang)
        print()
        if not lang:
            return '\n<pre><code>%s</code></pre>\n' % \
                mistune.escape(code)
        lexer = get_lexer_by_name(lang, stripall=True)
        formatter = HtmlFormatter()
        return highlight(code, lexer, formatter)


def markdown_format(post):
    renderer = HighlightRenderer()
    markdown = mistune.Markdown(renderer=renderer)
    return markdown(post)

from django.db import models
from django.utils import timezone
# from django.contrib.auth.models import User
from django.contrib.auth import get_user_model
from django.shortcuts import reverse
from django.template.defaultfilters import slugify

from taggit.managers import TaggableManager
# from markdownx.models import MarkdownxField
from bs4 import BeautifulSoup
from pygments import highlight, formatters, lexers


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset().filter(status='published')


class ImageStore(models.Model):
    title = models.TextField()
    cover = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = "Images"


class Post(models.Model):
    tags = TaggableManager()
    objects = models.Manager()  # The default manager.
    published = PublishedManager()  # Our custom manager.
    CONTENT_LANGUAGE_CHOICES = (
        ('html', 'HTML',),
        ('mark', 'Markdown'),
    )
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    language = models.CharField(max_length=20,
                                choices=CONTENT_LANGUAGE_CHOICES,
                                default='html',
                                help_text="Select Content Language")
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish', blank=True, null=True)
    author = models.ForeignKey(get_user_model(),
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    body_content = models.TextField(blank=True, null=True, editable=False)
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES,
                              default='draft')

    class Meta:
        ordering = ('-publish',)

    def save(self, *args, **kwargs):
        print("Save method called")
        if not self.id:
            self.slug = slugify(self.title)
        self.body_content = markdown_format(self.body)

        super(Post, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        published_localtime = timezone.localtime(self.publish)
        # return reverse('blog:post_detail',
        #                args=[self.publish.year,
        #                      self.publish.month,
        #                      self.publish.day,
        #                      self.slug])
        return reverse('blog:post_detail',
                       args=[published_localtime.year,
                             published_localtime.strftime('%m'),
                             published_localtime.strftime('%d'),
                             self.slug])


class HighlightCode(models.Model):
    body = models.TextField()
    body_highlighted = models.TextField(editable=False, blank=True)

    def save(self, force_insert=False, force_update=False):
        self.body_highlighted = self.highlight_code(self.body)
        super(HighlightCode, self).save(force_insert, force_update)

    def highlight_code(self, html):
        #  create BeautifulSoup object using self.body content

        soup = BeautifulSoup(html)
        #  collect all pre block content
        preblocks = soup.findAll('pre')
        for pre in preblocks:
            # all changes are occured inline
            if pre.has_key('class'):
                try:
                    # list to string conversion
                    code = ''.join([str(item) for item in pre.contents])
                    code = self.unescape_html(code)
                    lexer = lexers.get_lexer_by_name(pre['class'][0])
                    formatter = formatters.HtmlFormatter()
                    code_hl = highlight(code, lexer, formatter)
                    pre.replaceWith(BeautifulSoup(code_hl))
                except:
                    pass
        #  retuned changed soup content
        return str(soup)

    def unescape_html(self, html):
        html = html.replace('&lt;', '<')
        html = html.replace('&gt;', '>')
        html = html.replace('&amp;', '&')
        return html


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.name, self.post)

blog/forms.py
# blog/forms.py

from django import forms

from .models import Comment, Post, ImageStore

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                            widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class NewPost(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['tags', 'title', 'slug', 'author', 'body', 'publish', 'status',]


class ImageUploadForm(forms.ModelForm):

    class Meta:
        model = ImageStore
        fields = ['title', 'cover']

blog/views.py
import csv
import io
# import os

from django.core.mail import send_mail
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.db.models import Count
from django.http import FileResponse, HttpResponse, StreamingHttpResponse
from django.shortcuts import get_object_or_404, render
from django.template import loader
from django.urls import reverse_lazy
from django.views.generic import DetailView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from taggit.models import Tag
from reportlab.pdfgen import canvas
from django.views.generic.dates import (
            TodayArchiveView,
            ArchiveIndexView,
            YearArchiveView,
            MonthArchiveView,
            )

from .forms import CommentForm, EmailPostForm, ImageUploadForm
from .models import Post, HighlightCode, ImageStore


class ImageView(ListView):
    model = ImageStore
    template_name = 'image_view.html'


class ImageUploadView(CreateView):
    model = ImageStore
    form_class = ImageUploadForm
    template_name = 'image_upload.html'
    success_url = reverse_lazy('blog:books')


def post_list(request, tag_slug=None):
    posts = Post.published.all()
    paginator = Paginator(posts, 15)
    page_number = request.GET.get('page')
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        # deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # if page is out of range deliver last page of results.
        posts = paginator.page(paginator.num_pages)

    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        posts = posts.filter(tags__in=[tag])

    return render(request, 'blog/home.html', {'posts': posts, 'tag': tag})

# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     template_name = 'blog/home.html'


class NewPostView(CreateView):
    model = Post
    template_name = 'blog/post_new.html'
    fields = ['tags', 'language', 'title', 'author', 'body', 'status', ]


class PostUpdate(UpdateView):
    model = Post
    template_name = 'blog/post_update.html'
    fields = ['tags', 'title', 'slug', 'body', 'status', ]


class PostDelete(DeleteView):
    model = Post
    template_name = 'blog/post_delete.html'
    success_url = reverse_lazy('blog:home')


# class PostDetailView(DetailView):
#     model = Post
#     template_name = 'blog/post_detail.html'


def post_detail(request, year, month, day, post):

    # post = get_object_or_404(Post, slug=post,
    #                         status='published',
    #                         publish__year=year,
    #                         publish__month=month,
    #                         publish__day=day)
    post = get_object_or_404(
                            Post, slug=post,
                            status='published',
                            )
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    # list of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(
                                        tags__in=post_tags_ids
                                        ).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by(
                                        '-same_tags', '-publish')[:4]

    return render(
                request,
                'blog/post_detail.html',
                {
                    'post': post,
                    'new_comment': new_comment,
                    'comment_form': comment_form,
                    'comments': comments,
                    'similar_posts': similar_posts
                }
                )


def post_share(request, post_id):

    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = '{}({}) recommends you reading "\
                    {}"'.format(cd['name'], cd['email'], post.title)
            message = 'Read "{}" at {}\n\n{}\'s comments {}'.format(
                                                        post.title,
                                                        post_url,
                                                        cd['name'],
                                                        cd['comments']
                                                                    )
            send_mail(subject, message, 'admin@myblog.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(
                request,
                'blog/share.html',
                {'post': post, 'form': form, 'sent': sent})


def some_view(request):

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'
    writer = csv.writer(response)
    writer.writerow(['First row', 'Foo', 'Bar', 'Baz'])
    writer.writerow(
                ['Second row', 'A', 'B', 'C', '"Testing"', "Here's a quote"]
                  )

    return response


class Echo:
    """An object that implements just the write method of the file-like
    interface.
    """
    def write(self, value):
        """Write the value by returning it, instead of storing in a buffer."""
        return value


def some_streaming_csv_view(request):
    """A view that streams a large CSV file."""
    # Generate a sequence of rows. The range is based on the maximum number of
    # rows that can be handled by a single sheet in most spreadsheet
    # applications.
    rows = (["Row {}".format(idx), str(idx)] for idx in range(65536))
    pseudo_buffer = Echo()
    writer = csv.writer(pseudo_buffer)
    response = StreamingHttpResponse(
                                    (writer.writerow(row) for row in rows),
                                    content_type="text/csv")
    response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'
    return response


def Some_view(request):

    # Create the HttpResponse object with the appropriate CSV header.
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="somefilename.csv"'
    # The data is hard-coded here, but you could load it from a database or
    # some other source.
    csv_data = (
        ('First row', 'Foo', 'Bar', 'Baz'),
        ('Second row', 'A', 'B', 'C', '"Testing"', "Here's a quote"),
    )
    t = loader.get_template('my_template_name.txt')
    c = {'data': csv_data}
    response.write(t.render(c))
    return response


def pdf_view(request):
    # Create a file-like buffer to receive PDF data.
    buffer = io.BytesIO()
    body = Post.published.get(id=1).body
    body = str(body)
    # Create the PDF object, using the buffer as its "file."
    p = canvas.Canvas(buffer)
    # Draw things on the PDF. Here's where the PDF generation happens.
    # See the ReportLab documentation for the full list of functionality.
    p.drawString(100, 100, body)
    # Close the PDF object cleanly, and we're done.
    p.showPage()
    p.save()
    # FileResponse sets the Content-Disposition header so that browsers
    # present the option to save the file.
    buffer.seek(0)
    return FileResponse(buffer, filename='hello.pdf')


class PostTodayArchiveView(TodayArchiveView):
    queryset = Post.published.all()
    date_field = "updated"
    allow_future = True


class PostArchiveIndexView(ArchiveIndexView):
    queryset = Post.published.all()
    date_field = "updated"
    allow_future = True


class PostYearArchiveView(YearArchiveView):
    queryset = Post.published.all()
    date_field = "publish"
    make_object_list = True
    allow_future = True


class PostMonthArchiveView(MonthArchiveView):
    queryset = Post.published.all()
    date_field = "publish"
    allow_future = True


class HighlightView(DetailView):
    model = HighlightCode
    template_name = 'blog/highlight_code.html'


def about_me(request):

    return render(request, 'blog/about.html')

blog/templates/blog/about.html
{% extends 'base.html' %}


{% block content %}
  <h1>Hey, I am <strong>shahid ullah</strong></h1>
  <h3>I am complete python Nut</h3>
  <p>I have been programming About 2 Years.
    I have experience in <strong>Python, Django, Git, JavaScript, Bootstrap, HTML, CSS</strong>
  </p>
  <!-- HTML generated using hilite.me -->
  <div
    style="background: #272822; overflow:auto;width:auto;border:solid gray;border-width:.1em .1em .1em .8em;padding:.2em .6em;">
    <table>
      <tr>
        <td>
          <pre style="margin: 0; line-height: 125%">1
  </pre>
        </td>
        <td>
          <pre style="margin: 0; line-height: 125%"><span style="color: #66d9ef">with</span> <span style="color: #f8f8f2">open(</span><span style="color: #e6db74">&quot;workData.txt&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&quot;r&quot;</span><span style="color: #f8f8f2">)</span> <span style="color: #66d9ef">as</span> <span style="color: #f8f8f2">work_data:</span>
      <span style="color: #f8f8f2">work_data_contents</span> <span style="color: #f92672">=</span> <span style="color: #f8f8f2">work_data</span><span style="color: #f92672">.</span><span style="color: #f8f8f2">readlines()</span>
  
  <span style="color: #f8f8f2">work_data_contents</span><span style="color: #f92672">.</span><span style="color: #f8f8f2">insert(</span><span style="color: #ae81ff">1</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&quot;This goes between line 1 and 2</span><span style="color: #ae81ff">\n</span><span style="color: #e6db74">&quot;</span><span style="color: #f8f8f2">)</span>
  
  <span style="color: #75715e"># Re-open in write-only format to overwrite old file</span>
  <span style="color: #66d9ef">with</span> <span style="color: #f8f8f2">open(</span><span style="color: #e6db74">&quot;workData.txt&quot;</span><span style="color: #f8f8f2">,</span> <span style="color: #e6db74">&quot;w&quot;</span><span style="color: #f8f8f2">)</span> <span style="color: #66d9ef">as</span> <span style="color: #f8f8f2">work_data:</span>
      <span style="color: #f8f8f2">work_dataContents</span> <span style="color: #f92672">=</span> <span style="color: #e6db74">&quot;&quot;</span><span style="color: #f92672">.</span><span style="color: #f8f8f2">join(work_data_contents)</span>
      <span style="color: #f8f8f2">work_data</span><span style="color: #f92672">.</span><span style="color: #f8f8f2">write(work_data_contents)</span>
  </pre>
        </td>
      </tr>
    </table>
  </div>
  
  {% endblock content %}

blog/templates/blog/highlight_code.html
{% extends 'base.html' %}

{% block content %}
    {% if object.body_highlighted %}
        {{ object.body_highlighted}}
    {% else %}
        {{ object.body}}
  {% endif %}
{% endblock content %}

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}

    {% for post in posts %}
      <ul class="post-list">
        <li>
          <h2>
            <a class="post-link" href="{{ post.get_absolute_url }}">{{ post.title }}</a>
          </h2>
          <span class="post-meta">{{ post.publish }}</span>
          <span class="post-meta">{{ post.slug }}</span>
        </li>
        <p>
          Tags:
          {% for tag in post.tags.all %}
            <a href="{% url "blog:post_list_by_tag" tag.slug %}"> {{ tag.name }}</a>
            {% if not forloop.last %}, {% endif %}
          {% endfor %}
        </p>
      </ul>
    {% endfor %}
    {% include "pagination.html" with page=posts %}

{% endblock content %}

blog/templates/blog/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>
    

blog/templates/blog/post_archive.html
<ul>
        {% for date in date_list %}
            date: {{ date }}
        {% endfor %}
        {% for article in latest %}
        <li>{{ article.pub_date }}: {{ article.title }}</li>
        {% endfor %}
</ul>

blog/templates/blog/post_archive_day.html
# blog/templates/blog/post_archive_today.html


<h1>{{ day }}</h1>
<ul>
{% for article in object_list %}
<li>{{ article.pub_date|date:"F j, Y" }}: {{ article.title }}</li>
{% endfor %}
</ul>
<p>
{% if previous_day %}
Previous Day: {{ previous_day }}
{% endif %}
{% if previous_day and next_day %}--{% endif %}
{% if next_day %}
Next Day: {{ next_day }}
{% endif %}
</p>

blog/templates/blog/post_archive_month.html
<ul>
    {% for article in object_list %}
    <li>{{ article.pub_date|date:"F j, Y" }}: {{ article.title }}</li>
    {% endfor %}
</ul>
<p>
{% if previous_month %}
Previous Month: {{ previous_month|date:"F Y" }}
{% endif %}
{% if next_month %}
Next Month: {{ next_month|date:"F Y" }}
{% endif %}
</p>

blog/templates/blog/post_archive_year.html
<ul>
    {%for date in date_list %}
        <li>{{ date|date }}</li>
    {% endfor %}
</ul>
<div>
    <h1>All Articles for {{ year|date:"Y" }}</h1>
    {% for obj in object_list %}
    <p>
    {{ obj.title }} - {{ obj.pub_date|date:"F j, Y" }}
    </p>
    {% endfor %}
</div>

blog/templates/blog/post_delete.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        <h2>Delete</h2>
        <p>Are you sure, you want to delete {{ post.title }}?</p>
        <button type="submit">Delete</button>
    </form>
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{# {% load markdownify %} #}

{% block content %}
    <img src="{% static 'ParetoPrincipe.png' %}"/>
    <h2>{{ post.title}}
        {% comment %}
        <a href="{% url "blog:post_share" post.id %}">
        Share this post
        <a href="{% url "blog:post_update" post.id %}">
            update
        </a>
        <a href="{% url "blog:post_delete" post.id %}">
            Delete
        </a>
        {% endcomment %}
    </h2>
    {# <div class="content-body">{{ post.body|markdown|safe}}</div> #}
    <div class="content-body">{{ post.body_content|safe}}</div>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <p>
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}


    {% with comments.count as total_comments %}
        <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }}
            {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {{ comment_form|crispy}}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}


{% endblock content %}

blog/templates/blog/post_new.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>New Post</h2>
    <form action="", method="POST">
        {% csrf_token %}
        {{ form |crispy}}
        <button type="submit">Create</button>
    </form>
    {{ form.media }}

{% endblock content %}

blog/templates/blog/post_update.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update</button>
    </form>
    {{ form.media }}
{% endblock content %}

blog/templates/blog/share.html
{% extends "base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
{% if sent %}
<h1>E-mail successfully sent</h1>
<p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="." method="post">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}