blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'
urlpatterns = [
    # path('', views.PostListView.as_view(), name='home'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
        views.post_detail,
        name='post_detail'),
    path('csv/',views.Some_view, name='csv'),
    path('highlight/<int:pk>/',views.HighlightView.as_view(), name='hightlight'),
    path('pdf/',views.pdf_view, name='pdf'),
    path('new/', views.NewPostView.as_view(), name='post_new'),
    path('<int:pk>/update/', views.PostUpdate.as_view(), name='post_update'),
    path('<int:pk>/delete/', views.PostDelete.as_view(), name='post_delete'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('today/', views.PostTodayArchiveView.as_view(),name="today_post"),
    path('archive/', views.PostArchiveIndexView.as_view(),name="today_archive"),
    path('<int:year>/', views.PostYearArchiveView.as_view(),name="post_year_archive"),
    path('<int:year>/<int:month>/', views.PostMonthArchiveView.as_view(month_format="%m"),name="archive_month_numeric"),
    path('<int:year>/<str:month>/', views.PostMonthArchiveView.as_view(),name="archive_month"),

    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('about/', views.about_me, name='about_me'),
    path('books/', views.ImageView.as_view(), name='books'),
    path('upload/', views.ImageUploadView.as_view(), name='image_upload'),
    path('', views.post_list, name='home'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from django.conf import settings
from django.conf.urls.static import static

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
                                 name='django.contrib.sitemaps.views.sitemap'),
    path('markdownx/', include('markdownx.urls')),
    path('users/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

templates/base.html
{% load static %}
{% load blog_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

		<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static 'highlight.css' %}">
    <link rel="stylesheet" href="{% static 'custom_style.css' %}">
    <title>Learn Django</title>
</head>

<body>
    <nav class="navbar navbar-expand-md">
        <div class="container-fluid">
            <a href="{% url 'blog:home' %}" class="navbar-brand mr-3">Programming Tutorial Hub</a>
            <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <div class="navbar-nav">
                    <a href="#" class="nav-item nav-link">Services</a>
                    <a href="{% url 'blog:about_me' %}" class="nav-item nav-link">About</a>
                    <a href="#" class="nav-item nav-link">Contact</a>
                    <a href="{% url 'blog:books' %}" class="nav-item nav-link">Favourite Books</a>
                    <a href="{% url 'blog:post_new' %}" class="nav-item nav-link">+</a>
                </div>
            </div>
        </div>
    </nav>

    <div class="container">
        <!--Row with three equal columns-->
        <div class="row">
            <div class="col-xl-2">

            </div>
            <div class="col-xl-8">
                {% block content %}
                {% endblock content %}
            </div>
            <div class="col-xl-2">
              {% block sidebar %}
              {% endblock sidebar %}
            </div>
        </div>
    </div>

    </div>
      <hr>
      <footer>
          <div class="row">
              <div class="col-md-1">
              </div>
              <div class="col-md-5">
                  <p>Copyright &copy; 2020 Programming Tutorial Hub</p>
              </div>
              <div class="col-md-5 text-md-right">
                  <a href="#" class="text-dark">Terms of Use</a>
                  <span class="text-muted mx-2">|</span>
                  <a href="#" class="text-dark">Privacy Policy</a>
              </div>
              <div class="col-md-1">
              </div>
          </div>
      </footer>
    </div>
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</body>

</html>

templates/image_upload.html
<!-- templates/post.html -->
<h1>Upload</h1>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Upload</button>
</form>

templates/image_view.html
<!-- templates/home.html -->
{% extends 'base.html' %}
{% block content %}

  <h1>My Favourite Reading list</h1>
  <ul>
    {% for post in object_list %}
      {# <h2>{{ post.title }}</h2> #}
      <img src="{{ post.cover.url }}" alt="{{ post.title }} width="600" height="500">
      <p>{{ post.cover }}</p>
    {% endfor %}
  </ul>
{% endblock content %}

templates/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page={{ page.previous_page_number }}">Previous</a>
        {% endif %}
        <span class="current">
            Page {{page.number}} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Next</a>
        {% endif %}
    </span>
</div>